import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Order comes from each doc's `sidebar_position` and each folder's `_category_.json`.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Imprint', href: '/imprint'},
  ],
};

export default sidebars;
